### ISSUE TITLE
connection to the mitre taxii server doesn't work anymore

### ISSUE THREAD

**Issue by ianlav01** [siriussecurity/dettectinator#16]
It is not possible for dettectinator to connect to the taxii server from mitre. The script cannot create yaml files anymore because of this.
<img width="742" alt="image" src="https://github.com/siriussecurity/dettectinator/assets/115007081/ec3ebe10-91b2-4895-b3e9-0ef3cc0a8c17">

**Comment by rubinatorz** [comment]
hi @ianlav01 

That's because the TAXII server of MITRE is down. That happens from time to time, so I would like to recommend to use the local STIX repository option.

In dettectinator you have this command line parameter:
 
 -s STIX_LOCATION, --stix_location STIX_LOCATION
                        Local STIX repository location.

Use this option and refer to a local path where you've cloned the MITRE CTI repository from:
https://github.com/mitre/cti

This is much faster also.
