### ISSUE TITLE
Question: Have you ever dealt/Applied Dettectinator to QRadar?

### ISSUE THREAD

**Issue by Hackcidental** [siriussecurity/dettectinator#9]
Hi,

Thank you for the good work with Dettectinator.
The title pretty much sums it up.
We're trying to implement Dettectinator with QRadar, I think that with the CVS import we can do something, but maybe you've faced this already in the past.
Thank you!

**Comment by mveken** [comment]
Hi, 
No we do not and we don't have access to a Qradar instance to try things out. I briefly looked at the API specs and this looks like what you might want to use: https://www.ibm.com/docs/en/qsip/7.5?topic=apis-report-column-codes-report

Hope this helps, and otherwise look you said, if you're able to create a CSV with rules and techniques you van always use that for the import.

Regards, Martijn

**Comment by Hackcidental** [comment]
Hi,

Thank you for the answer.
I will look into the API you mention.
Regards,

Matteo

**Comment by mveken** [comment]
Yes, let me know if you can get it to work. It's hard for me to create something without access to Qradar, but always happy to help out if you run into any issues.
